export enum Configuration{
    PORT= 'PORT',
    HOST= 'HOST',
    USER= 'USER',
    PASSWORD= 'PASSWORD',
    DATABASE= 'DATABASE',
    JWTSECRET= 'JWT_SECRET',
    MAIL_HOSTNAME='MAIL_HOSTNAME',
    MAIL_USERNAME='MAIL_USERNAME',
    MAIL_PASSWORD='MAIL_PASSWORD',
    MAIL_REPLYTO='MAIL_REPLYTO'
}